sudo: required
language: ruby
services:
  - docker
rvm:
  - 2.4
  - 2.5
  - 2.6
before_install:
  - gem update --system
  - gem install bundler
addons:
  firefox: latest
git:
  depth: 1
script:
  - bundle exec jekyll build -d _site/wax
  - bundle exec rake wax:test
  - docker build -t ubuntu/wax .
